### ISSUE TITLE
Method picture for posting on the wall

### ISSUE THREAD

**Issue by sharkzp** [moomerman/facebook_oauth#6]
I'm trying to post picture on Facebook using gem facebook_oath.
And i getting 400 error. While using simple "message" posting everything goes right, but with picture everything goes wrong, and error 400 appears.
Do you have any clues? Thanks for any help.
client = FacebookOAuth::Client.new(:application_id => CONFIG[:facebook]['id'],
                                             :application_secret => CONFIG[:facebook]['secret'],
                                             :token => account.token)
          opts = {:name => 'trololo',
            :link => 'http://google.com.ua',
            :picture => "http://www.google.com.ua/images/logos/ps_logo2.png",
            :message => "trolololo",
          }
          r = client.user(user_id).feed(:create, opts)

**Comment by masahikoofjoytoy** [comment]
I tried now,  It was successful!
